# -*- coding: utf-8 -*-
"""09_06_2023_4potok.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QscJ79Z9SLQvS7Fyp9l9MaMPnD4HXPIa
"""

# Экспоненциальный поиск
def binar(arr, x):
  low = 0
  high = len(arr)-1
  index = -1
  while (low <= high) and (index == -1):
    mid = (low+high) // 2
    if arr[mid] == x:
      index = mid
    else:
      if x < arr[mid]:
        high = mid - 1
      else:
        low = mid + 1
  return index


def exp_serch(arr,x):
  if arr[0] == x:
    return 0
  index = 1
  while index < len(arr) and arr[index] <= x:
    index = index * 2
  return binar(arr[:min(index, len(arr))], x)

testarr = [1,2,3,4,5,7,9,10]
y = int(input("Введи число:"))

if exp_serch(testarr,y) != -1:
  print ("Элемен найден под индексом: ", exp_serch(testarr,y))
else:
  print ("Элемент не найден в массиве")

# Jump поиск
import math

def jump_search(arr,x):
  jump = int(math.sqrt(len(arr)))
  left = 0
  right = 0
  while left < len(arr) and arr[left] <= x:
    right = min(len(arr)-1, left + jump)
    if arr[left] <= x and arr[right] >= x:
      break
    left += jump
  if left >= len(arr) or arr[left] > x:
    return -1
  right = min(len(arr)-1, right)
  n = left
  while n <= right and arr[n] <= x:
    if arr[n] == x:
      return n
    n += 1
  return -1


testarr = [1,2,3,4,5,7,9,10]
y = int(input("Введи число:"))

if jump_search(testarr,y) != -1:
  print ("Элемен найден под индексом: ", jump_search(testarr,y))
else:
  print ("Элемент не найден в массиве")

# Интерполяционный поиск
def inter_search(arr,x):
  low = 0
  high = (len(arr)-1)
  while low <= high and x >= arr[low] and x <= arr[high]:
    index = low + int((x - arr[low]) * (high - low) / (arr[high] - arr[low]))
    if arr[index] == x:
      return index
    if arr[index] < x:
      low = index + 1
    else:
      high = index - 1
  return -1


testarr = [1,2,3,4,5,7,9,10]
y = int(input("Введи число:"))

if inter_search(testarr,y) != -1:
  print ("Элемен найден под индексом: ", inter_search(testarr,y))
else:
  print ("Элемент не найден в массиве")